config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users

  namespace :api do
    post '/auth/login', to: 'authentication#login'
    resources :users, only: [] do
      resources :posts, only: [:index] do
        resources :comments, only: %i[index create]
      end
    end

    resources :posts, only: [] do
      resources :comments, only: [:create]
    end
  end

  resources :users, only: %i[index show] do
    resources :posts, only: %i[index show]
  end

  resources :posts, only: [:index, :show, :new, :create, :destroy]
  resources :comments, only: [:new, :create, :destroy]

  resources :likes, only: [:create]
  root 'users#index'
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  belongs_to :post

  def post_comments_counter=(count)
    post.update_attribute 'comments_counter', count
  end
end

app/controllers/api/comments_controller.rb
class Api::CommentsController < ApiController
  def index
    @post = Post.find(params[:post_id])
    @comments = @post.comments

    render json: @comments
  end

  def create
    @post = Post.find(params[:post_id])

    @comment = Comment.new comment_params
    @comment.post = @post
    @comment.author = @post.author

    @comment.save! if @comment.valid?
    render json: @comment
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource

  before_action :authenticate_user!, only: [:create]

  def create
    @comment = Comment.new comment_params
    @author = current_user
    @comment.author = @author

    @comment.save if @comment.valid?
    redirect_to post_path(@comment.post)
  end

  def destroy
    Comment.destroy(params[:id])

    redirect_to :back
  end

  private

  def comment_params
    params.require(:comment).permit(:text, :post_id)
  end
end

app/views/comments/_comment.html.erb
<div class="rounded-lg bg-slate-50/80 w-full p-4 relative">
  <div class="flex items-center gap-x-4">
    <div class="shrink-0">
      <%= render partial: 'shared/avatar', locals: { photo: comment.author.photo } %>
    </div>
    <div>
      <div class="text-gray-600 text-sm"><%= comment.author.name %></div>
      <div class="text-sm"><%= comment.text %></div>
    </div>
  </div>
  <div class="absolute right-2 top-2">
    <%= render partial: 'comments/delete_button', locals: { comment_id: comment.id } if can? :destroy, comment %>
  </div>
</div>

app/views/comments/_delete_button.html.erb
<%= button_to comment_path(comment_id), method: :delete, class: "rounded p-1 bg-red-50 text-red-500" do %>
  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" class="w-4 h-4">
    <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
  </svg>
<% end %>

app/views/comments/_form.html.erb
<% input_classes = 'rounded border border-slate-200 w-full' %>
<%= form_with model: Comment, class: 'flex gap-x-4' do |form| %>
  <%= form.hidden_field :post_id, value: post.id %>
  <div class="w-full min-w-0">
    <%= form.text_field :text, placeholder: 'Your comment...', class: input_classes %>
  </div>
  <div>
    <button type="submit" class="rounded px-4 py-2 bg-white shadow-md outline outline-slate-200">
      Comment
    </button>
  </div>
<% end %>