config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users

  namespace :api do
    post '/auth/login', to: 'authentication#login'
    resources :users, only: [] do
      resources :posts, only: [:index] do
        resources :comments, only: %i[index create]
      end
    end

    resources :posts, only: [] do
      resources :comments, only: [:create]
    end
  end

  resources :users, only: %i[index show] do
    resources :posts, only: %i[index show]
  end

  resources :posts, only: [:index, :show, :new, :create, :destroy]
  resources :comments, only: [:new, :create, :destroy]

  resources :likes, only: [:create]
  root 'users#index'
end

app/models/user.rb
class User < ApplicationRecord
  after_initialize :set_defaults
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :posts, foreign_key: 'author_id'
  has_many :comments, foreign_key: 'author_id'
  has_many :likes, foreign_key: 'author_id'

  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def admin?
    role == 'admin'
  end

  def last_three_posts
    posts.last(3)
  end

  private

  def set_defaults
    self.photo = 'https://xsgames.co/randomusers/assets/avatars/male/71.jpg' if photo.blank?
  end
end

app/controllers/api/users_controller.rb
class Api::UsersController < ApiController
  skip_before_action :authorize_request, only: [:create], raise: false

  def index
    @users = User.all

    render json: @users
  end

  def show
    @user = User.find(params[:id])

    render json: @user
  end
end

app/controllers/users/devise_controller.rb
class Users::DeviseController < ApplicationController
  layout 'application'

  class Responder < ActionController::Responder
    def to_turbo_stream
      controller.render(options.merge(formats: :html))
    rescue ActionView::MissingTemplate => e
      raise e if get?

      if has_errors? && default_action
        render rendering_options.merge(formats: :html, status: :unprocessable_entity)
      else
        redirect_to navigation_location
      end
    end
  end

  self.responder = Responder
  respond_to :html, :turbo_stream
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/views/users/_user.html.erb
<%= link_to user_path(user) do %>
  <div class="rounded-lg border-2 border-slate-100 bg-slate-50 w-full">
    <div class="flex gap-x-8">
      <div class="w-32 h-32 shrink-0">
        <img class="max-w-full max-h-full rounded-lg" src="<%= user.photo %>" alt="Profile picture">
      </div>
      <div class="min-w-0 flex flex-col gap-y-1 my-3">
        <div class="text-2xl font-mono">
          <%= user.name %>
        </div>
        <div class="mb-auto">
          <p class="text-gray-500 text-sm truncate">
            <%= user.bio %>
          </p>
        </div>
        <div>
          <%= render layout: "shared/tag" do %>
            <%= pluralize(user.posts_counter, 'Post') %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/users/_user_card.html.erb
<div class="flex gap-x-4">
  <div class="w-48 h-48 shrink-0">
    <img class="max-w-full max-h-full h-full rounded-lg" src="<%= user.photo %>" alt="Profile picture">
  </div>
  <div class="flex flex-col my-4">
    <div class="text-2xl font-mono mb-2">
      <%= user.name %>
    </div>
    <div class="text-gray-400 text-xs italic">
      <%= user.posts_counter == 0 ? 'No posts yet by this author' : "#{pluralize(user.posts_counter, 'post')} has been published" %>
    </div>
    <div class="text-gray-400 text-xs italic">
      Joined in <%= user.created_at.strftime("%B, %e at %H:%M") %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div>
  <div class="flex flex-col gap-y-4">
    <%= render @users %>
  </div>
</div>

app/views/users/show.html.erb
<div class="flex flex-col gap-y-6">
  <div class="flex gap-x-4">
    <div class="w-48 h-48 shrink-0">
      <img class="max-w-full max-h-full h-full rounded-lg" src="<%= @user.photo %>" alt="Profile picture">
    </div>
    <div class="flex flex-col my-4">
      <div class="text-2xl font-mono mb-2">
        <%= @user.name %>
      </div>
      <div class="text-gray-400 text-xs italic">
        <%= @user.posts_counter == 0 ? 'No posts yet by this author' : "#{pluralize(@user.posts_counter, 'post')} has been published" %>
      </div>
      <div class="text-gray-400 text-xs italic">
        Joined in <%= @user.created_at.strftime("%B, %e at %H:%M") %>
      </div>
    </div>
  </div>
  <div class="rounded-lg bg-slate-50 w-full p-4">
    <h2 class="text-lg mb-1">Bio</h2>
    <p class="text-gray-600"><%= @user.bio %></p>
  </div>
  <%= render @user.last_three_posts %>
  <div class="flex justify-center gap-x-4">
    <%= link_to user_posts_path(@user) do %>
      <span class="rounded px-4 py-2 bg-white shadow-md outline outline-slate-200">
        See all posts
      </span>
    <% end %>
    <%= link_to new_post_path do %>
      <span class="rounded px-4 py-2 text-white bg-primary-400 shadow-md">
        Create new post
      </span>
    <% end %>
  </div>
</div>