config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users

  namespace :api do
    post '/auth/login', to: 'authentication#login'
    resources :users, only: [] do
      resources :posts, only: [:index] do
        resources :comments, only: %i[index create]
      end
    end

    resources :posts, only: [] do
      resources :comments, only: [:create]
    end
  end

  resources :users, only: %i[index show] do
    resources :posts, only: %i[index show]
  end

  resources :posts, only: [:index, :show, :new, :create, :destroy]
  resources :comments, only: [:new, :create, :destroy]

  resources :likes, only: [:create]
  root 'users#index'
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :comments, dependent: :delete_all
  has_many :likes, dependent: :delete_all

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def user_posts_counter=(count)
    author.update_attribute 'posts_counter', count
  end

  def last_five_comments
    comments.last(5)
  end
end

app/controllers/api/posts_controller.rb
class Api::PostsController < ApiController
  before_action :fetch_author, only: %i[index show]
  before_action :authorize_request

  def index
    @posts = @author ? @author.posts.includes(:comments, :author) : Post.includes(:comments, :author).all

    render json: @posts
  end

  private

  def fetch_author
    return nil unless params[:user_id]

    @author = User.find(params[:user_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource

  before_action :fetch_author, only: %i[index show destroy]
  before_action :authenticate_user!, only: %i[new create]

  def index
    @posts = @author ? @author.posts.includes(:comments, :author) : Post.includes(:comments, :author).all
  end

  def show
    @post = @author ? @author.posts.find(params[:id]) : Post.find(params[:id])
  end

  def new; end

  def create
    @post = Post.new post_params
    @author = current_user
    @post.author = @author

    if @post.valid?
      @post.save

      redirect_to user_posts_path(@author)
    else
      redirect_to new_post_path
    end
  end

  def destroy
    Post.destroy(params[:id])

    redirect_to @author ? user_posts_path(@author) : posts_path
  end

  private

  def fetch_author
    return nil unless params[:user_id]

    @author = User.find(params[:user_id])
  end

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/views/posts/_delete_button.html.erb
<%= button_to post_path(post_id), method: :delete, class: "flex items-center gap-x-2 rounded px-2 py-1 bg-red-50 shadow-md text-red-500" do %>
  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" class="w-4 h-4">
    <path stroke-linecap="round" stroke-linejoin="round" d="M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 01-2.244 2.077H8.084a2.25 2.25 0 01-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 00-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 013.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 00-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 00-7.5 0" />
  </svg>
  <span class="text-xs tracking-wide font-semibold">Delete</span>
<% end %>

app/views/posts/_form.html.erb
<% input_classes = 'rounded border border-slate-200 w-96' %>
<%= form_with model: Post, class: 'flex flex-col gap-y-6' do |form| %>
  <div>
    <%= form.text_field :title, placeholder: 'Title', class: input_classes %>
  </div>
  <div>
    <%= form.text_area :text, placeholder: 'Post description...', class: input_classes %>
  </div>
  <div>
    <button type="submit" class="rounded px-4 py-2 bg-white shadow-md outline outline-slate-200">
      Register
    </button>
  </div>
<% end %>

app/views/posts/_post.html.erb
<%= link_to user_post_path(post.author, post) do %>
  <div class="rounded-lg bg-slate-50 w-full p-4">
    <h2 class="text-lg mb-1"><%= post.title %></h2>
    <p class="text-gray-600"><%= post.text %></p>
    <div class="flex divide-x gap-x-2 mt-4">
      <div>
        <%= render layout: "shared/tag" do %>
          <div class="flex gap-x-1 items-center font-medium">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" class="w-3 h-3">
              <path stroke-linecap="round" stroke-linejoin="round" d="M2.25 12.76c0 1.6 1.123 2.994 2.707 3.227 1.087.16 2.185.283 3.293.369V21l4.076-4.076a1.526 1.526 0 011.037-.443 48.282 48.282 0 005.68-.494c1.584-.233 2.707-1.626 2.707-3.228V6.741c0-1.602-1.123-2.995-2.707-3.228A48.394 48.394 0 0012 3c-2.392 0-4.744.175-7.043.513C3.373 3.746 2.25 5.14 2.25 6.741v6.018z" />
            </svg>
            <span><%= post.comments_counter %></span>
          </div>
        <% end %>
        <%= render layout: "shared/tag" do %>
          <div class="flex gap-x-1 items-center font-medium">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" class="w-3 h-3">
              <path stroke-linecap="round" stroke-linejoin="round" d="M21 8.25c0-2.485-2.099-4.5-4.688-4.5-1.935 0-3.597 1.126-4.312 2.733-.715-1.607-2.377-2.733-4.313-2.733C5.1 3.75 3 5.765 3 8.25c0 7.22 9 12 9 12s9-4.78 9-12z" />
            </svg>
            <span><%= post.likes_counter %></span>
          </div>
        <% end %>
      </div>
      <div class="pl-2 flex gap-x-2">
        <%= render partial: 'likes/form', locals: { post_id: post.id } %>
        <%= render partial: 'posts/delete_button', locals: { post_id: post.id } if can? :destroy, post %>
      </div>
    </div>
  </div>
<% end %>

app/views/posts/index.html.erb
<div class="flex flex-col gap-y-6">
  <%= render partial: 'users/user_card', locals: { user: @author } unless @author.nil? %>
  <div class="flex flex-col gap-y-8">
    <% @posts.each do |post| %>
      <div class="flex flex-col gap-y-2">
        <%= render post %>
        <%= render post.last_five_comments %>
      </div>
    <% end %>
  </div>
  <div class="mx-auto">
    <a class="rounded px-4 py-2 bg-white shadow-md outline outline-slate-200">
      Pagination
    </a>
  </div>
</div>

app/views/posts/new.html.erb
<div class="flex flex-col">
  <div class="text-xl mb-2">Create new post</div>
  <%= render 'form' %>
</div>

app/views/posts/show.html.erb
<div class="flex flex-col gap-y-6">
  <div class="rounded-lg bg-slate-50 w-full p-4">
    <div class="flex flex-col gap-x-2 items-baseline mb-2">
      <span class="text-lg"><%= @post.title %></span>
      <span class="text-xs text-gray-600 italic">By <%= @post.author.name %></span>
    </div>
    <p class="text-gray-600"><%= @post.text %></p>
    <div class="flex divide-x gap-x-2 mt-4">
      <div>
        <%= render layout: "shared/tag" do %>
          <div class="flex gap-x-1 items-center font-medium">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" class="w-3 h-3">
              <path stroke-linecap="round" stroke-linejoin="round" d="M2.25 12.76c0 1.6 1.123 2.994 2.707 3.227 1.087.16 2.185.283 3.293.369V21l4.076-4.076a1.526 1.526 0 011.037-.443 48.282 48.282 0 005.68-.494c1.584-.233 2.707-1.626 2.707-3.228V6.741c0-1.602-1.123-2.995-2.707-3.228A48.394 48.394 0 0012 3c-2.392 0-4.744.175-7.043.513C3.373 3.746 2.25 5.14 2.25 6.741v6.018z" />
            </svg>
            <span><%= @post.comments_counter %></span>
          </div>
        <% end %>
        <%= render layout: "shared/tag" do %>
          <div class="flex gap-x-1 items-center font-medium">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" class="w-3 h-3">
              <path stroke-linecap="round" stroke-linejoin="round" d="M21 8.25c0-2.485-2.099-4.5-4.688-4.5-1.935 0-3.597 1.126-4.312 2.733-.715-1.607-2.377-2.733-4.313-2.733C5.1 3.75 3 5.765 3 8.25c0 7.22 9 12 9 12s9-4.78 9-12z" />
            </svg>
            <span><%= @post.likes_counter %></span>
          </div>
        <% end %>
      </div>
      <div class="pl-2 flex gap-x-2">
        <%= render partial: 'likes/form', locals: { post_id: @post.id } %>
        <%= render partial: 'posts/delete_button', locals: { post_id: @post.id } if can? :destroy, @post %>
      </div>
    </div>
  </div>
  <div class="flex flex-col gap-y-2">
    <%= render @post.comments  %>
  </div>
  <div>
    <%= render partial: 'comments/form', locals: { post: @post }  %>
  </div>
</div>